# This is a basic workflow to help you get started with Actions

name: Flush stale pending orders

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the dev2 branch
  schedule:
  - cron: "0 15 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    name: set up Systems
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Starts actions
        run: echo *** FLUSH STALE PENDING ORDERS ***

      # Runs a set of commands using the runners shell
      - name: Run flushing script
        run: curl ${{PENDING_ORDER_URL}}
